context:
  version: "0.1.1"
  python_min: "3.11"

recipe:
  name: diracx
  version: ${{ version }}

build:
  number: 0

outputs:
  - package:
      name: diracx-api

    source:
      - url: https://pypi.org/packages/source/d/diracx-api/diracx_api-${{ version }}.tar.gz
        sha256: 70887e5059436ec61bb4bf2de5792daeadcdbd0a352353dbeff3cfe69cfbba74
      - url: https://raw.githubusercontent.com/DIRACGrid/diracx/refs/tags/v${{ version }}/LICENSE
        sha256: bb2af8a15ea39a351e7a95d93cf8e4251c1ae6ae4cac8ee3a89cf9b155cd6e54

    build:
      script: ${{ PYTHON }} -m pip install .
      noarch: python

    requirements:
      host:
        - python ${{ python_min }}.*
        - hatchling
        - hatch-vcs
        - pip
      run:
        - python >=${{ python_min }}
        - diracx-client ==${{ version }}
        - diracx-core ==${{ version }}
        - httpx
        - zstandard

    tests:
      - python:
          python_version: ${{ python_min }}.*
          imports:
            - diracx.api
          pip_check: true

    about:
      summary: Python API for interacting with DiracX services

  - package:
      name: diracx-cli

    source:
      - url: https://pypi.org/packages/source/d/diracx-cli/diracx_cli-${{ version }}.tar.gz
        sha256: 7857902fb81763416cf7ff5f92c39501a4bfbb6d43717a586aca33da5a148a07
      - url: https://raw.githubusercontent.com/DIRACGrid/diracx/refs/tags/v${{ version }}/LICENSE
        sha256: bb2af8a15ea39a351e7a95d93cf8e4251c1ae6ae4cac8ee3a89cf9b155cd6e54

    build:
      script: ${{ PYTHON }} -m pip install .
      python:
        entry_points:
          - dirac = diracx.cli:app
      noarch: python

    requirements:
      host:
        - python ${{ python_min }}.*
        - hatchling
        - hatch-vcs
        - pip
      run:
        - python >=${{ python_min }}
        - diraccfg
        - diracx-api ==${{ version }}
        - diracx-client ==${{ version }}
        - diracx-core ==${{ version }}
        - gitpython
        - pydantic >=2.10
        - pyyaml
        - rich
        - typer >=0.15.4

    tests:
      - python:
          python_version: ${{ python_min }}.*
          imports:
            - diracx.cli
          pip_check: true
      - script:
          - dirac --help

    about:
      summary: Command line interface for DiracX

  - package:
      name: diracx-client

    source:
      - url: https://pypi.org/packages/source/d/diracx-client/diracx_client-${{ version }}.tar.gz
        sha256: f48e40bf9910656ec7f74f247f033203caa8c3bebe01fae55db995fef12c492b
      - url: https://raw.githubusercontent.com/DIRACGrid/diracx/refs/tags/v${{ version }}/LICENSE
        sha256: bb2af8a15ea39a351e7a95d93cf8e4251c1ae6ae4cac8ee3a89cf9b155cd6e54

    build:
      script: ${{ PYTHON }} -m pip install .
      noarch: python

    requirements:
      host:
        - python ${{ python_min }}.*
        - hatchling
        - hatch-vcs
        - pip
      run:
        - python >=${{ python_min }}
        - azure-core
        - diracx-core ==${{ version }}
        - httpx
        - isodate
        - pyjwt

    tests:
      - python:
          python_version: ${{ python_min }}.*
          imports:
            - diracx.client
          pip_check: true

    about:
      summary: Client library for DiracX services from OpenAPI specifications

  - package:
      name: diracx-core

    source:
      - url: https://pypi.org/packages/source/d/diracx-core/diracx_core-${{ version }}.tar.gz
        sha256: db8228dd8e1a6e2745f55310230f4a2a184cb3938a58ab0c6e683c85ad723376
      - url: https://raw.githubusercontent.com/DIRACGrid/diracx/refs/tags/v${{ version }}/LICENSE
        sha256: bb2af8a15ea39a351e7a95d93cf8e4251c1ae6ae4cac8ee3a89cf9b155cd6e54

    build:
      script: ${{ PYTHON }} -m pip install .
      noarch: python

    requirements:
      host:
        - python ${{ python_min }}.*
        - hatchling
        - hatch-vcs
        - pip
      run:
        - python >=${{ python_min }}
        - aiobotocore >=2.15
        - botocore >=1.35
        - cachetools
        - diraccommon >=9.0.0
        - email-validator
        - gitpython
        - joserfc >=1.1.0
        - pydantic-settings
        - pydantic >=2.10
        - pyyaml
        - sh

    tests:
      - python:
          python_version: ${{ python_min }}.*
          imports:
            - diracx.core
          pip_check: true

    about:
      summary: Common code used by all DiracX packages
      license: GPL-3.0-only

  - package:
      name: diracx-db

    source:
      - url: https://pypi.org/packages/source/d/diracx-db/diracx_db-${{ version }}.tar.gz
        sha256: 12f5552c06ea5028c19f92608edb506c1a4f935902ce4f6fce9178ccb0b0e2ed
      - url: https://raw.githubusercontent.com/DIRACGrid/diracx/refs/tags/v${{ version }}/LICENSE
        sha256: bb2af8a15ea39a351e7a95d93cf8e4251c1ae6ae4cac8ee3a89cf9b155cd6e54

    build:
      script: ${{ PYTHON }} -m pip install .
      noarch: python

    requirements:
      host:
        - python ${{ python_min }}.*
        - hatchling
        - hatch-vcs
        - pip
      run:
        - python >=${{ python_min }}
        - diracx-core ==${{ version }}
        - opensearch-py
        - aiohttp>=3.12.14,<4 # Needed for opensearch-py's async extra
        - pydantic >=2.10
        - python-dateutil
        - sqlalchemy-with-aiomysql
        - sqlalchemy-with-aiosqlite
        - uuid-utils

    tests:
      - python:
          python_version: ${{ python_min }}.*
          imports:
            - diracx.db
          pip_check: true

    about:
      summary: Data Access Layer for DiracX database functionalities

  - package:
      name: diracx-logic

    source:
      - url: https://pypi.org/packages/source/d/diracx-logic/diracx_logic-${{ version }}.tar.gz
        sha256: 647ef2438687f9d57f655fdf9339462cb7473837af5a9d70f742c91e8bdd74d8
      - url: https://raw.githubusercontent.com/DIRACGrid/diracx/refs/tags/v${{ version }}/LICENSE
        sha256: bb2af8a15ea39a351e7a95d93cf8e4251c1ae6ae4cac8ee3a89cf9b155cd6e54

    build:
      script: ${{ PYTHON }} -m pip install .
      noarch: python

    requirements:
      host:
        - python ${{ python_min }}.*
        - hatchling
        - hatch-vcs
        - pip
      run:
        - python >=${{ python_min }}
        - cachetools
        - diraccommon >=9.0.0
        - diracx-core ==${{ version }}
        - diracx-db ==${{ version }}
        - joserfc
        - pydantic >=2.10
        - uuid-utils

    tests:
      - python:
          python_version: ${{ python_min }}.*
          imports:
            - diracx.logic
          pip_check: true

    about:
      summary: Business Logic Layer containing DiracX logic
      description: ''
      license: GPL-3.0-only

  - package:
      name: diracx-routers

    source:
      - url: https://pypi.org/packages/source/d/diracx-routers/diracx_routers-${{ version }}.tar.gz
        sha256: cb78f0b13785773020606f0ebbdc5a04ce1af158610202df69b087f0757e4662
      - url: https://raw.githubusercontent.com/DIRACGrid/diracx/refs/tags/v${{ version }}/LICENSE
        sha256: bb2af8a15ea39a351e7a95d93cf8e4251c1ae6ae4cac8ee3a89cf9b155cd6e54

    build:
      script: ${{ PYTHON }} -m pip install .
      noarch: python

    requirements:
      host:
        - python ${{ python_min }}.*
        - hatchling
        - hatch-vcs
        - pip
      run:
        - python >=${{ python_min }}
        - cachetools
        - diracx-core ==${{ version }}
        - diracx-db ==${{ version }}
        - diracx-logic ==${{ version }}
        - diracx-tasks ==${{ version }}
        - fastapi >=0.121.0
        - httpx
        - joserfc
        - opentelemetry-api >=1.40.0
        - opentelemetry-exporter-otlp >=1.40.0
        - opentelemetry-instrumentation-fastapi >=0.61b0
        - opentelemetry-instrumentation-logging >=0.61b0
        - opentelemetry-sdk >=1.40.0
        - pydantic >=2.10
        - python-dotenv
        - python-multipart
        - uvicorn

    tests:
      - python:
          python_version: ${{ python_min }}.*
          imports:
            - diracx.routers
          pip_check: true

    about:
      summary: FastAPI routers providing HTTP endpoints for DiracX services

  - package:
      name: diracx-tasks

    source:
      - url: https://pypi.org/packages/source/d/diracx-tasks/diracx_tasks-${{ version }}.tar.gz
        sha256: 1520d9b68b917b2cea0b212b32471927d0b841456b21670d92d89ba06301d601
      - url: https://raw.githubusercontent.com/DIRACGrid/diracx/refs/tags/v${{ version }}/LICENSE
        sha256: bb2af8a15ea39a351e7a95d93cf8e4251c1ae6ae4cac8ee3a89cf9b155cd6e54

    build:
      script: ${{ PYTHON }} -m pip install .
      python:
        entry_points:
          - diracx-task-run = diracx.tasks.task_run:main
      noarch: python

    requirements:
      host:
        - python ${{ python_min }}.*
        - hatchling
        - hatch-vcs
        - pip
      run:
        - python >=${{ python_min }}
        - croniter
        - diracx-core ==${{ version }}
        - diracx-db ==${{ version }}
        - diracx-logic ==${{ version }}
        - fastapi >=0.121.0
        - hiredis
        - msgpack-python
        - opentelemetry-api
        - pydantic >=2.10
        - python-dateutil
        - redis-py

    tests:
      - python:
          python_version: ${{ python_min }}.*
          imports:
            - diracx.tasks
          pip_check: true

    about:
      summary: Asynchronous task system for DiracX

  - package:
      name: diracx-testing

    source:
      - url: https://pypi.org/packages/source/d/diracx-testing/diracx_testing-${{ version }}.tar.gz
        sha256: 76a2f9d7690c5713e4b597e952a249cc27bb5bc7ba8823f316ea60bc0f884ab9
      - url: https://raw.githubusercontent.com/DIRACGrid/diracx/refs/tags/v${{ version }}/LICENSE
        sha256: bb2af8a15ea39a351e7a95d93cf8e4251c1ae6ae4cac8ee3a89cf9b155cd6e54

    build:
      script: ${{ PYTHON }} -m pip install .
      noarch: python

    requirements:
      host:
        - python ${{ python_min }}.*
        - hatchling
        - hatch-vcs
        - pip
      run:
        - python >=${{ python_min }}
        - diracx-core ==${{ version }}
        - httpx
        - joserfc
        - pytest
        - pytest-asyncio >=1.1.0
        - pytest-cov
        - pytest-github-actions-annotate-failures
        - pytest-lazy-fixtures
        - pytest-xdist
        - uuid-utils

    tests:
      - python:
          python_version: ${{ python_min }}.*
          imports:
            - diracx.testing
          pip_check: true

    about:
      summary: Testing utilities and fixtures for DiracX development

  - package:
      name: diracx

    source:
      - url: https://pypi.org/packages/source/d/diracx/diracx-${{ version }}.tar.gz
        sha256: ea2138579f7ccf12904d84e3db422f39bdd14c2e7c6d6a1dfcf636420c68cf43
      - url: https://raw.githubusercontent.com/DIRACGrid/diracx/refs/tags/v${{ version }}/LICENSE
        sha256: bb2af8a15ea39a351e7a95d93cf8e4251c1ae6ae4cac8ee3a89cf9b155cd6e54

    build:
      script: ${{ PYTHON }} -m pip install .
      noarch: python

    requirements:
      host:
        - python ${{ python_min }}.*
        - hatchling
        - hatch-vcs
        - pip
      run:
        - python >=${{ python_min }}
        - diracx-api ==${{ version }}
        - diracx-cli ==${{ version }}
        - diracx-client ==${{ version }}
        - diracx-core ==${{ version }}

    tests:
      - python:
          python_version: ${{ python_min }}.*
          imports:
            - diracx
            - diracx.core
            - diracx.api
            - diracx.cli
            - diracx.client
          pip_check: true

    about:
      summary: Client installation for users of DiracX installations

about:
  summary: A framework for managing grid-style resources
  homepage: https://diracx.diracgrid.org/
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  feedstock-name: diracx
  recipe-maintainers:
    - chrisburr
