context:
  version: "0.4.1"
  python_min: "3.11"

recipe:
  name: diracx
  version: ${{ version }}

build:
  number: 0

outputs:
  - package:
      name: diracx-api

    source:
      - url: https://pypi.org/packages/source/d/diracx-api/diracx_api-${{ version }}.tar.gz
        sha256: bf15ad62c93cad61333a31ec5cd45ee52f933f84cdbf561903f8956c11dbe679
      - url: https://raw.githubusercontent.com/DIRACGrid/diracx/refs/tags/v${{ version }}/LICENSE
        sha256: bb2af8a15ea39a351e7a95d93cf8e4251c1ae6ae4cac8ee3a89cf9b155cd6e54

    build:
      script: ${{ PYTHON }} -m pip install .
      noarch: python

    requirements:
      host:
        - python ${{ python_min }}.*
        - hatchling
        - hatch-vcs
        - pip
      run:
        - python >=${{ python_min }}
        - diracx-client ==${{ version }}
        - diracx-core ==${{ version }}
        - httpx2
        - zstandard

    tests:
      - python:
          python_version: ${{ python_min }}.*
          imports:
            - diracx.api
          pip_check: true

    about:
      summary: Python API for interacting with DiracX services

  - package:
      name: diracx-cli

    source:
      - url: https://pypi.org/packages/source/d/diracx-cli/diracx_cli-${{ version }}.tar.gz
        sha256: ad67618e0b23fefd3a5daee07c21b8ffe8232615d583c49f3ee0753f3c140a89
      - url: https://raw.githubusercontent.com/DIRACGrid/diracx/refs/tags/v${{ version }}/LICENSE
        sha256: bb2af8a15ea39a351e7a95d93cf8e4251c1ae6ae4cac8ee3a89cf9b155cd6e54

    build:
      script: ${{ PYTHON }} -m pip install .
      python:
        entry_points:
          - dirac = diracx.cli:app
      noarch: python

    requirements:
      host:
        - python ${{ python_min }}.*
        - hatchling
        - hatch-vcs
        - pip
      run:
        - python >=${{ python_min }}
        - diraccfg
        - diracx-api ==${{ version }}
        - diracx-client ==${{ version }}
        - diracx-core ==${{ version }}
        - gitpython
        - pydantic >=2.10
        - pyyaml
        - rich
        - typer >=0.15.4

    tests:
      - python:
          python_version: ${{ python_min }}.*
          imports:
            - diracx.cli
          pip_check: true
      - script:
          - dirac --help

    about:
      summary: Command line interface for DiracX

  - package:
      name: diracx-client

    source:
      - url: https://pypi.org/packages/source/d/diracx-client/diracx_client-${{ version }}.tar.gz
        sha256: aff7e97a4da421388d00facc38fcc0ea39bb5ab01d9ef63f77f193698ff7dd3d
      - url: https://raw.githubusercontent.com/DIRACGrid/diracx/refs/tags/v${{ version }}/LICENSE
        sha256: bb2af8a15ea39a351e7a95d93cf8e4251c1ae6ae4cac8ee3a89cf9b155cd6e54

    build:
      script: ${{ PYTHON }} -m pip install .
      noarch: python

    requirements:
      host:
        - python ${{ python_min }}.*
        - hatchling
        - hatch-vcs
        - pip
      run:
        - python >=${{ python_min }}
        - azure-core
        - aiohttp >=3.0 # Needed for azure-core's aio extra
        - diracx-core ==${{ version }}
        - httpx2
        - isodate
        - pyjwt

    tests:
      - python:
          python_version: ${{ python_min }}.*
          imports:
            - diracx.client
          pip_check: true

    about:
      summary: Client library for DiracX services from OpenAPI specifications

  - package:
      name: diracx-core

    source:
      - url: https://pypi.org/packages/source/d/diracx-core/diracx_core-${{ version }}.tar.gz
        sha256: 5041ee698f9082850747eb315115fbb25ccd0485582b135cf3c62d239d271c35
      - url: https://raw.githubusercontent.com/DIRACGrid/diracx/refs/tags/v${{ version }}/LICENSE
        sha256: bb2af8a15ea39a351e7a95d93cf8e4251c1ae6ae4cac8ee3a89cf9b155cd6e54

    build:
      script: ${{ PYTHON }} -m pip install .
      noarch: python

    requirements:
      host:
        - python ${{ python_min }}.*
        - hatchling
        - hatch-vcs
        - pip
      run:
        - python >=${{ python_min }}
        - cachetools
        - diraccommon >=9.0.18
        - email-validator
        - gitpython
        - joserfc >=1.5.0
        - pydantic-settings
        - pydantic >=2.10
        - pyyaml
        - sh
        - signurlarity >=0.3.1

    tests:
      - python:
          python_version: ${{ python_min }}.*
          imports:
            - diracx.core
          pip_check: true

    about:
      summary: Common code used by all DiracX packages
      license: GPL-3.0-only

  - package:
      name: diracx-db

    source:
      - url: https://pypi.org/packages/source/d/diracx-db/diracx_db-${{ version }}.tar.gz
        sha256: 74b9c1b707795db3204f89771882e9ee076c261acfc6759058ad4e63953693c3
      - url: https://raw.githubusercontent.com/DIRACGrid/diracx/refs/tags/v${{ version }}/LICENSE
        sha256: bb2af8a15ea39a351e7a95d93cf8e4251c1ae6ae4cac8ee3a89cf9b155cd6e54

    build:
      script: ${{ PYTHON }} -m pip install .
      noarch: python

    requirements:
      host:
        - python ${{ python_min }}.*
        - hatchling
        - hatch-vcs
        - pip
      run:
        - python >=${{ python_min }}
        - diracx-core ==${{ version }}
        - opensearch-py
        - aiohttp>=3.12.14,<4 # Needed for opensearch-py's async extra
        - pydantic >=2.10
        - python-dateutil
        - sqlalchemy-with-aiomysql
        - sqlalchemy-with-aiosqlite
        - uuid-utils

    tests:
      - python:
          python_version: ${{ python_min }}.*
          imports:
            - diracx.db
          pip_check: true

    about:
      summary: Data Access Layer for DiracX database functionalities

  - package:
      name: diracx-logic

    source:
      - url: https://pypi.org/packages/source/d/diracx-logic/diracx_logic-${{ version }}.tar.gz
        sha256: 83887d63ce14a8082b42837ae7b05465625b5be271581e60fb6807e224b4854b
      - url: https://raw.githubusercontent.com/DIRACGrid/diracx/refs/tags/v${{ version }}/LICENSE
        sha256: bb2af8a15ea39a351e7a95d93cf8e4251c1ae6ae4cac8ee3a89cf9b155cd6e54

    build:
      script: ${{ PYTHON }} -m pip install .
      noarch: python

    requirements:
      host:
        - python ${{ python_min }}.*
        - hatchling
        - hatch-vcs
        - pip
      run:
        - python >=${{ python_min }}
        - cachetools
        - diraccommon >=9.0.18
        - diracx-core ==${{ version }}
        - diracx-db ==${{ version }}
        - joserfc
        - pydantic >=2.10
        - uuid-utils

    tests:
      - python:
          python_version: ${{ python_min }}.*
          imports:
            - diracx.logic
          pip_check: true

    about:
      summary: Business Logic Layer containing DiracX logic
      description: ''
      license: GPL-3.0-only

  - package:
      name: diracx-routers

    source:
      - url: https://pypi.org/packages/source/d/diracx-routers/diracx_routers-${{ version }}.tar.gz
        sha256: 55c1fe4d71f29d28bf9feb14da671140e159923d05190118f3aac9905de96204
      - url: https://raw.githubusercontent.com/DIRACGrid/diracx/refs/tags/v${{ version }}/LICENSE
        sha256: bb2af8a15ea39a351e7a95d93cf8e4251c1ae6ae4cac8ee3a89cf9b155cd6e54

    build:
      script: ${{ PYTHON }} -m pip install .
      noarch: python

    requirements:
      host:
        - python ${{ python_min }}.*
        - hatchling
        - hatch-vcs
        - pip
      run:
        - python >=${{ python_min }}
        - cachetools
        - diracx-core ==${{ version }}
        - diracx-db ==${{ version }}
        - diracx-logic ==${{ version }}
        - diracx-tasks ==${{ version }}
        - fastapi >=0.121.0
        - httpx2
        - joserfc
        - opentelemetry-api >=1.40.0
        - opentelemetry-exporter-otlp >=1.40.0
        - opentelemetry-instrumentation-fastapi >=0.61b0
        - opentelemetry-instrumentation-logging >=0.61b0
        - opentelemetry-sdk >=1.40.0
        - pydantic >=2.10
        - python-dotenv
        - python-multipart
        - uvicorn

    tests:
      - python:
          python_version: ${{ python_min }}.*
          imports:
            - diracx.routers
          pip_check: true

    about:
      summary: FastAPI routers providing HTTP endpoints for DiracX services

  - package:
      name: diracx-tasks

    source:
      - url: https://pypi.org/packages/source/d/diracx-tasks/diracx_tasks-${{ version }}.tar.gz
        sha256: d678bed1bfb0058b26290192416da3fd9a2c7e197d299eb04b51bcbb816116d9
      - url: https://raw.githubusercontent.com/DIRACGrid/diracx/refs/tags/v${{ version }}/LICENSE
        sha256: bb2af8a15ea39a351e7a95d93cf8e4251c1ae6ae4cac8ee3a89cf9b155cd6e54

    build:
      script: ${{ PYTHON }} -m pip install .
      python:
        entry_points:
          - diracx-task-run = diracx.tasks.task_run:main
      noarch: python

    requirements:
      host:
        - python ${{ python_min }}.*
        - hatchling
        - hatch-vcs
        - pip
      run:
        - python >=${{ python_min }}
        - croniter
        - diracx-core ==${{ version }}
        - diracx-db ==${{ version }}
        - diracx-logic ==${{ version }}
        - fastapi >=0.121.0
        - hiredis
        - msgpack-python
        - opentelemetry-api
        - pydantic >=2.10
        - python-dateutil
        - redis-py

    tests:
      - python:
          python_version: ${{ python_min }}.*
          imports:
            - diracx.tasks
          pip_check: true

    about:
      summary: Asynchronous task system for DiracX

  - package:
      name: diracx-testing

    source:
      - url: https://pypi.org/packages/source/d/diracx-testing/diracx_testing-${{ version }}.tar.gz
        sha256: e28c3ea46a479619a09edb3bb7747cfcc07c9f9ade108dec9f53fd982b4a095b
      - url: https://raw.githubusercontent.com/DIRACGrid/diracx/refs/tags/v${{ version }}/LICENSE
        sha256: bb2af8a15ea39a351e7a95d93cf8e4251c1ae6ae4cac8ee3a89cf9b155cd6e54

    build:
      script: ${{ PYTHON }} -m pip install .
      noarch: python

    requirements:
      host:
        - python ${{ python_min }}.*
        - hatchling
        - hatch-vcs
        - pip
      run:
        - python >=${{ python_min }}
        - diracx-core ==${{ version }}
        - freezegun
        - httpx2
        - joserfc
        - pytest
        - pytest-asyncio >=1.1.0
        - pytest-cov
        - pytest-github-actions-annotate-failures
        - pytest-lazy-fixtures
        - pytest-xdist
        - sqlalchemy
        - uuid-utils

    tests:
      - python:
          python_version: ${{ python_min }}.*
          imports:
            - diracx.testing
          pip_check: true

    about:
      summary: Testing utilities and fixtures for DiracX development

  - package:
      name: diracx

    source:
      - url: https://pypi.org/packages/source/d/diracx/diracx-${{ version }}.tar.gz
        sha256: 86357906de67a11a3846249c614518452bf52f256a85d197039840f9ca1dbc93
      - url: https://raw.githubusercontent.com/DIRACGrid/diracx/refs/tags/v${{ version }}/LICENSE
        sha256: bb2af8a15ea39a351e7a95d93cf8e4251c1ae6ae4cac8ee3a89cf9b155cd6e54

    build:
      script: ${{ PYTHON }} -m pip install .
      noarch: python

    requirements:
      host:
        - python ${{ python_min }}.*
        - hatchling
        - hatch-vcs
        - pip
      run:
        - python >=${{ python_min }}
        - diracx-api ==${{ version }}
        - diracx-cli ==${{ version }}
        - diracx-client ==${{ version }}
        - diracx-core ==${{ version }}

    tests:
      - python:
          python_version: ${{ python_min }}.*
          imports:
            - diracx
            - diracx.core
            - diracx.api
            - diracx.cli
            - diracx.client
          pip_check: true

    about:
      summary: Client installation for users of DiracX installations

about:
  summary: A framework for managing grid-style resources
  homepage: https://diracx.diracgrid.org/
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  feedstock-name: diracx
  recipe-maintainers:
    - chrisburr
